### ISSUE TITLE
Inconsistency when calculating entanglement, possibly because of wrong graphs from stabilizers

### ISSUE THREAD

**Issue by royess** [Krastanov/QuantumClifford.jl#57]
I implemented two ways of calculating bipartite entanglement entropy base on this repo. One is by clipping algorithm. (Ref: Phys. Rev. B 100, 134306 (2019).) The other is by calculating the rank of bipartite adjacency matrix obtained by `Graphs.Graph(s::AbstractStabilizer)`. (Ref: arXiv:quant-ph/0602096.) And I also used Qiskit to cross check my results, using "statevector_simulator" backend.

In my 800 test cases, clipping algorithm agrees with Qiskit simulation. But there are 30 cases that entropy values from graphs differ by 1 or 2. So I think this may be a result of wrong graphs with more or less edges between two subsystems.

To help reproduce the issue:
- Codes to calculate entanglement entropy and run tests: https://github.com/royess/QuantumClifford.jl/tree/dev-clipping
- Codes to generate Qiskit data: https://github.com/royess/test-stab-entanglement/blob/main/get_data.py
- My test data in HDF5: [stab_ent.zip](https://github.com/Krastanov/QuantumClifford.jl/files/8822538/stab_ent.zip)

I know the issue involves many implementation details. I am willing to do more checks if needed.

**Comment by royess** [comment]
I find a simple example:
```julia
julia> g = SimpleGraphFromIterator((Edge(1,2),Edge(1,3)))
{3, 2} undirected simple Int64 graph

julia> g
{3, 2} undirected simple Int64 graph

julia> Stabilizer(g)
+ XZZ
+ ZX_
+ Z_X
```

And in fact, the graph state should be:
$$
| g \rangle = \frac{1}{2\sqrt{2}} (| 000 \rangle + | 001 \rangle + | 010 \rangle + | 011 \rangle +| 100 \rangle - | 101 \rangle - | 110 \rangle + | 111 \rangle ).
$$

And it is not stabilized by `+ ZX_` or `+ Z_X`.

**Comment by Krastanov** [comment]
Thanks for sharing this fork, the work there seems very interesting! Could you elaborate a bit on how one can reproduce the bug? It seems you are suggesting it is based on something related to the generation of a graph out of a stabilizer. That is implemented here https://github.com/Krastanov/QuantumClifford.jl/blob/master/src/graphs.jl#L4= and it is indeed very poorly tested and as of yet quite unused, so bugs might be lurking there.

**Comment by royess** [comment]
Thanks for your reply! To reproduce, please following these steps:

1. Clone and setup environment. `HDF5.jl` is additionally required.
2. Create `test/qiskit_data` and put `stab_ent.h5` in the folder. The HDF5 file is zipped in [stab_ent.zip](https://github.com/Krastanov/QuantumClifford.jl/files/8822538/stab_ent.zip).
3. At the end of `test/test_entanglement.jl`, keep `test_with_qiskit() ` and comment other calls of test functions.
4. Run `julia --project=.. runtests.jl` in `test`. You can set log level to allow debug information on failed tests.

Currently I am still not very sure where the problem is. I am working on more tests.

**Comment by Krastanov** [comment]
Could you help me verify one of the qiskit results? This is taken from your test file (neat way to do the tests, I would like to adopt some of this cross-validation approach you are using): 

```
entanglement_qiskit = 0.9999999999999999
leftend:rightend = 2:2
+ YYY
- XXY
+ Z_X
```

So, now I will try to compute the entropy of that same state after partial trace over the second or the third qubit (I am doing both, because there might also be an off-by-one error between python and julia code).

```
julia> s = S"+ YYY
       - XXY
       + Z_X"

julia> traceout!(copy(s),[2])
+ Z_X
+ ___
+ ___

julia> traceout!(copy(s),[3])
+ ZZ_
+ ___
+ ___
```

Both of these partial traces result in a tableau of rank 1. A 3 qubit state constrained by only one stabilizer is the equal mixture of 2^(3-1) kets, i.e. the entropy would be `3-1 = 2`. Maybe I am misunderstanding how the entropy function works in qiskit, so any comments would be appreciated.

Below is the code I used to find this example:
```
entropy(state) = (nqubits(state)-rank(state))

begin
    data_path = "./stab_ent.h5"
    test_sizes_qiskit = [3]#[3, 4, 6, 8]
    num_repeat = 200
    HDF5.h5open(data_path, "r") do f
        for test_size in test_sizes_qiskit
            grp = f["size$test_size"]
            for i_repeat in 1:1#num_repeat
                # load from qiskit data
                xzs = convert(Matrix{Bool}, grp["xzs"][:,:,i_repeat]) # Bool is not supported in HDF5.jl
                xzs = transpose(xzs)
                phases = grp["phases"][:,i_repeat]
                leftend = grp["leftend"][i_repeat] + 1
                rightend = grp["rightend"][i_repeat] + 1
                entanglement_qiskit = grp["entanglement"][i_repeat]
                # calculate by our approaches
                s = Stabilizer(phases, xzs)
                #entanglement_clipped = entanglement_cont(copy(s), (leftend, rightend))
                #entanglement_graph = entanglement_from_graph(s, leftend:rightend)
                entanglement_new = entropy(traceout!(MixedDestabilizer(s), leftend+1:rightend+1))
                try
                    @assert entanglement_new ≈ entanglement_qiskit
                catch
                    @show entanglement_new
                    @show entanglement_qiskit
                    @show leftend+1:rightend+1
                    println(s)
                end
            end
        end
    end
end
```

**Comment by royess** [comment]
I know very little about how `MixedDestabilizer` works, but I suppose this is not the correct way to calculate entanglement entropy. I try with 30 qubits, and take a subsystem of first 10 qubits.

```julia
julia> state = random_stabilizer(30);

julia> new_state = traceout!(copy(MixedDestabilizer(state)), 11:30);

julia> entanglement_from_graph(state, 1:10)
10

julia> entanglement_cont(state, (1,10))
10.0

julia> entropy(new_state) # I modify base to be 2 for consistency
-30

julia> nqubits(new_state)
30

julia> rank(new_state)
0
```

Note that entanglement entropy should be no more than 10, which is the size of the subsystem.

**Comment by royess** [comment]
****

> Could you help me verify one of the qiskit results? This is taken from your test file (neat way to do the tests, I would like to adopt some of this cross-validation approach you are using):
> 
> ```
> entanglement_qiskit = 0.9999999999999999
> leftend:rightend = 2:2
> + YYY
> - XXY
> + Z_X
> ```
> 
> So, now I will try to compute the entropy of that same state after partial trace over the second or the third qubit (I am doing both, because there might also be an off-by-one error between python and julia code).
> 
> ```
> julia> s = S"+ YYY
>              - XXY
>              + Z_X"
> 
> julia> traceout!(copy(s),[2])
> + Z_X
> + ___
> + ___
> 
> julia> traceout!(copy(s),[3])
> + ZZ_
> + ___
> + ___
> ```
> 
> Both of these partial traces result in a tableau of rank 1. A 3 qubit state constrained by only one stabilizer is the equal mixture of 2^(3-1) kets, i.e. the entropy would be `3-1 = 2`. But qiskit is saying it is `1`. Maybe I am misunderstanding how the entropy function works in qiskit, so any comments would be appreciated.
> 
> Below is the code I used to find this example:

Sorry I missed this one when replying. In this case, entanglement entropy is upper bounded by 1, which is the size of subsystem `2:2`. This is because the reduced density matrix of the subsystem is a 2-by-2 matrix. And it gets a maximal entropy value 1 when its eigenvalues are 1/2 and 1/2.

**Comment by Krastanov** [comment]
Oh, I think I see what the issue is now. The entropy I was computing assumed the traced out subsystems are still "there", just completely depolarized, which made the entropy much higher because of the extra degrees of freedom. Below is the corrected formula.

`MixedDestabilizer` is just a stabilizer tableau paired up with the destabilizers so that projection operations are faster. It also tracks rank, which makes it easier to work with mixed states.

The entropy of a mixed stabilizer state on `n` qubits of rank `r` is `-log(p)` where `p=2^(r-n)`, thus the entropy should be just `n-r`. The `traceout!` routine can be thought of as "partial trace followed by tensor product with identity matrices". We want to skip the tensor product part, i.e. we want to take into account that we have fewer qubits, i.e. the entropy will be `n-r-d` where `d` is the number of deleted qubits. The following seems to pass your tests:

```
function entropy(state, qubits_to_be_deleted)
    nb_of_qubits = nqubits(state)
    nb_of_deletions = length(qubits_to_be_deleted)
    new_state = traceout!(MixedDestabilizer(state), qubits_to_be_deleted) # TODO: this can be written better
    rank_after_deletion = rank(new_state)
    return nb_of_qubits - rank_after_deletion - nb_of_deletions
end

c = 0
begin
    data_path = "./stab_ent.h5"
    test_sizes_qiskit = [3, 4, 6, 8]
    num_repeat = 200
    HDF5.h5open(data_path, "r") do f
        for test_size in test_sizes_qiskit
            grp = f["size$test_size"]
            for i_repeat in 1:num_repeat
                # load from qiskit data
                xzs = convert(Matrix{Bool}, grp["xzs"][:,:,i_repeat]) # Bool is not supported in HDF5.jl
                xzs = transpose(xzs)
                phases = grp["phases"][:,i_repeat]
                leftend = grp["leftend"][i_repeat] + 1
                rightend = grp["rightend"][i_repeat] + 1
                entanglement_qiskit = grp["entanglement"][i_repeat]
                # calculate by our approaches
                s = Stabilizer(phases, xzs)
                #entanglement_clipped = entanglement_cont(copy(s), (leftend, rightend))
                #entanglement_graph = entanglement_from_graph(s, leftend:rightend)
                #entanglement_new = entropy(traceout!(MixedDestabilizer(s), leftend+1:rightend+1))
                entanglement_new = entropy(s, leftend:rightend)
                try
                    @assert abs(entanglement_new - entanglement_qiskit) < 0.01
                catch
                    @show entanglement_new
                    @show entanglement_qiskit
                    @show leftend+1:rightend+1
                    println(s)
                    global c += 1
                end
            end
        end
    end
end
```

**Comment by Krastanov** [comment]
There are probably still bugs to figure out inside of the graph related code, but at least now we have a short pure-julia piece of code against which to compare.

**Comment by royess** [comment]
> This part of the test set does check that conversion back and forth between graphs and stabilizers is correct. https://github.com/Krastanov/QuantumClifford.jl/blob/master/test/test_graphs.jl
> 
> The conversions are implemented in two independent ways for each direction, so it is probably not the place with highest probability of a bug.
> 
> Any chance the issue is related to working with mixed states? None of the graph related code knows how to deal with mixed states.

Sorry I missed another one. In my implementations, no mixed states are involved. So I think bugs are elsewhere.

**Comment by royess** [comment]
Great! Thanks for your codes and detailed explanation. I didn't notice we can calculate entropy in this way before doing implementation. That is really helpful.

By the way, I have done some tests that construct stabilizer state from graph. (Function `test_graph_entanglement`) So entanglement entropy can be accessed directly from graphs, no quantum states involved. But they also disagree. That may implied there are probably bugs in constructing stabilizer state from graph as well. But I cannot really imagine how.

**Comment by Krastanov** [comment]
I think you are right about the bug. I did the following silly thing instead of using your graph-based entanglement calculation and it is still causing mismatches `entanglement_graph = entropy(Stabilizer(Graph(s)), leftend:rightend)`. Basically, I convert the state to a graph and then back to a stabilizer and check the entropy, and there is indeed a mismatch.

**Comment by Krastanov** [comment]
That is a reasonable guess, but I would expect something like that to happen around n=64, as that is when weird off-by-one errors appear as we start having non-zero `jbig`.

I think the error is related to how the qubit indices are permuted when creating the graph, as seen here:

```
s = S"- _XZ
      + _ZX
      + ZXZ"

sg, g1, g2, g3 = graphstate(s)
c = graph_gate(g1,g2,g3,3)
traceout!(Stabilizer(Graph(s)), [1])
traceout!(copy(s), [1])
```

I should have a fix in a few minutes.

**Comment by Krastanov** [comment]
Hopefully this is fixed now! Thanks for reporting it! It was indeed an issue with how graphs are generated. The qubit indices get rearranged when that happens, and I was not correctly addressing that re-indexing. The issue appears only rarely, because only permutations with cycles longer than 2 were wrong, which does not happen very often.

**Comment by Krastanov** [comment]
> I plan to update the following things for the next step:
> 
>     * Test codes with your implementation entropy snippet.
> 
>     * More detailed tests on constructing stabilizer states from graphs, which seems easier than the opposite way to me.
> 
> 
> I will appreciate any suggestions.

That sounds great! More details on the two implementations you had would also be of interest. One thing you might have noticed is that it is very cumbersome to use the `jbig` and `jsmall` indexing and bit masking. It would be great to abstract that away in cleaner code, but that can wait for the moment. And do let me know if anything feels cumbersome or poorly documented -- I would like to fix that.

**Comment by Krastanov** [comment]
The fix is now published as version 0.5.1

**Comment by royess** [comment]
> Hopefully this is fixed now! Thanks for reporting it! It was indeed an issue with how graphs are generated. The qubit indices get rearranged when that happens, and I was not correctly addressing that re-indexing. The issue appears only rarely, because only permutations with cycles longer than 2 were wrong, which does not happen very often.

I repeat the tests. unfortunately bugs are not completely fixed. In 800 test cases, still one failed:
```julia
entanglement_qiskit = 2.0000000000000004
entanglement_clipped = 2.0
entanglement_graph = 3
leftend = 3
rightend = 6
s = + __YZ_X_X
+ XYYZYXX_
- XYZYZY_Y
+ _ZZ_YYY_
+ _XYY_YY_
+ X_XXZY_Y
- _YY_XYXY
+ Z__ZXZYY
collect(Graphs.edges(graph)) = Graphs.SimpleGraphs.SimpleEdge{Int64}[Edge 1 => 2, Edge 1 => 3, Edge 1 => 6, Edge 1 => 7, Edge 2 => 3, Edge 2 => 4, Edge 2 => 5, Edge 2 => 8, Edge 3 => 5, Edge 3 => 8, Edge 4 => 5, Edge 4 => 7, Edge 4 => 8, Edge 5 => 7, Edge 5 => 8, Edge 6 => 7, Edge 7 => 8]
```

To reproduce, please refer to `royess:dev-clipping` where I have merged your fixup.

**Comment by royess** [comment]
> * Test codes with your implementation entropy snippet.

Done. Please refer to `royess:dev-clipping` if needed.

**Comment by Krastanov** [comment]
Reopening to track the second bug

**Comment by Krastanov** [comment]
I made a small function to generate such wrong cases. It shows up only for number of qubits>=6, about 1 in 500 cases.

```
function entropy(state, qubits_to_be_deleted)
    nb_of_qubits = nqubits(state)
    nb_of_deletions = length(qubits_to_be_deleted)
    new_state = traceout!(MixedDestabilizer(state), qubits_to_be_deleted) # TODO: this can be written better
    rank_after_deletion = rank(new_state)
    return nb_of_qubits - rank_after_deletion - nb_of_deletions
end

function entanglement_from_graph_(state::Stabilizer, subsystem)
    graph = Graphs.Graph(state)
    adjmat = Matrix{Bool}(Graphs.adjacency_matrix(graph))
    other_subsystem = setdiff(1:nqubits(state), subsystem)
    subadjmat = adjmat[subsystem,other_subsystem]
    LinearAlgebra.rank(subadjmat)
end
##
function test(N,early=false)
    c = 0
    S = 10000
    for i in 1:S
        s = random_stabilizer(N)
        l,h = minmax(randperm(N)[[1,2]]...)
        if entropy(s, l:h) != entanglement_from_graph_(s, l:h)
            c+=1
            early && return l,h,s
        end
    end
    c/S
end
```

**Comment by Krastanov** [comment]
Could you share a reference that explains why the rank of the submatrix in the adjacency matrix gives the entanglement entropy?

Here is an example in which it is very easy to do the graph-based computation by hand:

Consider the following state which we will split in the halves [1,2,3] and [4,5,6]

```
s = S"  + XZZ_ZZ
        + ZX_ZZ_
        + Z_XZ_Z
        + _ZZXZZ
        + ZZ_ZXZ
        + Z_ZZZX"
```
For that state we have an adjacency matrix
```
julia> adjacency_matrix(Graph(s))
6×6 SparseArrays.SparseMatrixCSC{Int64, Int64} with 22 stored entries:
 ⋅  1  1  ⋅  1  1
 1  ⋅  ⋅  1  1  ⋅
 1  ⋅  ⋅  1  ⋅  1
 ⋅  1  1  ⋅  1  1
 1  1  ⋅  1  ⋅  1
 1  ⋅  1  1  1  ⋅
```

The submatrix we care about is
```
⋅  1  1
1  1  ⋅
1  ⋅  1
```

This submatrix obviously has a rank of 3.

However, the other entropy calculations give 2:
```
entropy(copy(s), 1:3) == 2
entanglement_cont(copy(s), 1:3) == 2
entanglement_from_graph(copy(s), 1:3) == 3
```

Because I did the calculation by hand with this simple example, I do not think the problem is a bug with the graph conversion.

**Comment by Krastanov** [comment]
There is a pretty silly typo in the above comment of mine that probably explains the bug. The rank is obviously 3 if we are talking about the +,* operations, not if we are talking about boolean operations where the rank is 2. I think this is the source of the bug: we are computing the wrong rank.

**Comment by Krastanov** [comment]
Interestingly, just this month someone asked the same question in the julia discourse https://discourse.julialang.org/t/rank-of-matrix-on-z2-field/81078/12

**Comment by Krastanov** [comment]
Here is the corrected function you can use in your PR.

```
function entanglement_from_graph(state::Stabilizer, subsystem)
    graph = Graphs.Graph(state)
    adjmat = Graphs.adjacency_matrix(graph)
    other_subsystem = setdiff(1:nqubits(state), subsystem)
    subadjmat = Nemo.matrix(Z2,collect(adjmat[subsystem,other_subsystem]))
    LinearAlgebra.rank(subadjmat)
end
```

**Comment by Krastanov** [comment]
I am closing this bug now. For future readers:

- the first half was an issue with incorrect indexing in `Graph(::Stabilizer)` that is now fixed
- the second half was an unrelated issue with how the code provided here is computing ranks of Boolean matrices

If there are other issues, let's start new bug reports so we can keep each thread single topic.

**Comment by royess** [comment]
Thanks for solving the problem! I think you are right. I assume it does a Z2 rank calculation without testing, but it does not.

> Could you share a reference that explains why the rank of the submatrix in the adjacency matrix gives the entanglement entropy?

Ref: arXiv:quant-ph/0602096. Please refer to eq 132 in Proposition 10.
